type: keyboard  # change to "gamepad" for joystick output

gamepad:
  backend: uinput

keyboard:
  backend: auto  # auto|uinput|pynput
  left_key: a
  right_key: d
  accel_key: w
  brake_key: space
  steer_threshold: 0.2
  steer_hold_threshold: 0.5
