type: keyboard  # change to "gamepad" for joystick output

gamepad:
  backend: uinput

keyboard:
  backend: auto  # auto|uinput|pynput
  left_key: a
  right_key: d
  accel_key: w
  brake_key: s
  steer_threshold: 0.45
  steer_hold_threshold: 0.45
  brake_steer_threshold: 0.3
  brake_steer_hold_threshold: 0.3
