gamepad:
  left:
    POINT:
      - type: axis
        control: LS_Y
        value: -1.0
    OPEN:
      - type: axis
        control: LS_Y
        value: 0.0
    THUMB_UP:
      - type: button
        control: LB
        pressed: true
  right:
    FIST:
      - type: axis
        control: RT
        value: 1.0
    PEACE:
      - type: button
        control: A
        pressed: true
    OPEN:
      - type: button
        control: X
        pressed: true
